baseURL= "https://nefertechie.github.io/"
languageCode= "en-us"
title= "Nefertechie Blog"
theme= "PaperMod"


[params]
  [[params.social]]
    icon= "twitter"
    url= "https://twitter.com/nefertechie"
  [[params.social]]
    icon= "linkedin"
    url= "https://www.linkedin.com/in/nefertechie"

[menu]
[[menu.main]]
  name= "Home"
  url= "/"
  weight= 10
[[menu.main]]
  name= "Blog"
  url= "/posts/"
  weight= 20
[[menu.main]]
  name= "Contents"
  url= "https://github.com/nefertechie"
  weight= 30
